from tkinter import *
import tkinter
import time 
top=Toplevel()
top.geometry("1600x800")
top.title("STUDENT PERFORMNCE CALCULATION : ")
top.configure(bg="white")
    
F1=Frame(top, width=1600, height=550, bg="white")
F1.pack(side=TOP)
F2=Frame(top, width=800, height=700, bg="white")
F2.pack(side=TOP)
c=Frame(top,width=800,height=700,bg="white")
c.pack(side=TOP)
l1 = Label(F1, font=('Times New Roman', 30 , 'bold' ), text="STUDENTS PERFORMANCE : " , fg="yellow",bg="black", bd=10,anchor='w')
l1.grid(row=0,column=0)
l1=Label(F2,text="\n\n\n\n\n",bg="white")
l1.grid(row=0,column=0)
l=Label(F2,font=('Times New Roman',20,'bold'),text=list,bg="light green")
l.grid(row=1,column=0)
l=Label(F2,text="\n\n\n\n\n",bg="white")
l.grid(row=2,column=0)
l2=Label(F2,font=('Times New Roman',20,'bold'),text="VALUE :",bg="green")
l2.grid(row=2,column=0)
l1=Label(F2,text="\n\n",bg="white")
l1.grid(row=3,column=0)
la=Label(c,text="CHECK ANOTHER SOURCE : ",font=('arial',15,'bold'),fg="blue",bg="white")
la.grid(row=0,column=0)
lb=Label(c,text="\t",bg="white")
lb.grid(row=0,column=1)
mb=Menubutton(c,text="Select",relief=RAISED,width=50,bg="pink",font=('Times New Roman',12,'bold'))
mb.grid(row=0,column=1)
mb.menu=Menu(mb,tearoff=0)
mb["menu"]=mb.menu
top.mainloop()